# Generated by Django 4.2.5 on 2023-09-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_course_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_head', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='data/media')),
                ('about_career_head', models.CharField(max_length=100)),
                ('about_career_para', models.TextField()),
                ('edu_path_head', models.CharField(max_length=100)),
                ('edu_path_stream', models.CharField(max_length=100)),
                ('edu_path_graduation', models.CharField(max_length=100)),
                ('edu_path_after_grad', models.CharField(max_length=100)),
                ('edu_path_post_grad', models.CharField(max_length=100)),
            ],
        ),
    ]
