# Generated by Django 4.2.5 on 2023-09-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='EduDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_head', models.CharField(max_length=100)),
                ('edu_path_stream', models.CharField(max_length=100)),
                ('edu_path_graduation', models.CharField(max_length=100)),
                ('edu_path_after_grad', models.CharField(max_length=100)),
                ('edu_path_post_grad', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='details',
            name='edu_path_after_grad',
        ),
        migrations.RemoveField(
            model_name='details',
            name='edu_path_graduation',
        ),
        migrations.RemoveField(
            model_name='details',
            name='edu_path_head',
        ),
        migrations.RemoveField(
            model_name='details',
            name='edu_path_post_grad',
        ),
        migrations.RemoveField(
            model_name='details',
            name='edu_path_stream',
        ),
    ]
