# Generated by Django 4.2.5 on 2023-09-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_edudetails_remove_details_edu_path_after_grad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edudetails',
            old_name='edu_path_after_grad',
            new_name='edu_after_grad',
        ),
        migrations.RenameField(
            model_name='edudetails',
            old_name='edu_path_graduation',
            new_name='edu_graduation',
        ),
        migrations.RenameField(
            model_name='edudetails',
            old_name='edu_path_post_grad',
            new_name='edu_post_grad',
        ),
        migrations.RenameField(
            model_name='edudetails',
            old_name='edu_path_stream',
            new_name='edu_stream',
        ),
    ]
